### PR TITLE
Fix ram_percentage.sh script when running on non-US locales

### PR DESCRIPTION
**Pull request by vinipsmaker**

### CODE REVIEW

**Comment by vinipsmaker** [comment]
> are there any other scripts which need this?

I only use the CPU and RAM script. Only RAM needed.

> Also without adding this, what's the output of free/vm_stat on your machine?

```
$ free
              total       usada       livre    compart.  buff/cache  disponível
Mem.:       7607696     4095064      542848      729176     2969784     2481620
Swap:      16777212      154320    16622892
```

```
$ vm_stat
zsh: command not found: vm_stat
zsh: exit 127   vm_stat
```

**Comment by casperdcl** [comment]
interesting. Can you post the output of this?

```
free | awk -v format="%3.1f%%\n" '$1 ~ /Mem/ {printf(format, 100*$3/$2)}'
```

**Comment by vinipsmaker** [comment]
The new command works regardless of my `LANG` env. However I don't think it's safe. Memory is translated as memória in my language. The translated string is probably just the first letters because it didn't fit in space. I bet it'd fail on other languages.

**Comment by casperdcl** [comment]
the only difference was "Mem:" versus "Mem.:" which seems more silly than a language change - it implies in future even `LANG=C` may break if it changes to add the extra dot.

**Pull request merged**
