### PR TITLE
use mpstat instead of iostat

### PR DESCRIPTION
**Pull request by nicky-zs**
iostat can not work in WSL on Win10

### CODE REVIEW

**Comment by ctjhoa** [comment]
Why do you change color names?

**Comment by nicky-zs** [comment]
It seems that "red", "blue", "yellow" names can not be recognized by all terminals, but "colourXXX" can.

**Comment by casperdcl** [comment]
Sounds like the colour change should be a different pr & discussion. Seems very weird to me.

**Comment by nicky-zs** [comment]
My bad. I'll close this pr and make two prs for these discussions.

**Pull request closed without merging**
